dist: trusty
language: cpp
compiler:
 - g++-7
 - clang-4.0
sudo: false
#branches:
#  only:
#    - master
#notifications:
#  email:
#    recipients:
#      - zamazan4ik@tut.by

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-7
    - clang-4.0
    - cmake

script:
 - cmake .